name: SonarQube Integration

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  sonarqube:
    name: SonarQube Integration
    runs-on: self-hosted # Use Windows runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Disabling shallow clone to improve relevancy of reporting

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install  # Install the dependencies from package.json

      - name: Install SonarQube Scanner globally using npm
        run: npm install -g sonar-scanner  # Install SonarQube Scanner globally

      - name: Run SonarQube Scan
        run: |
          sonar-scanner `
            -Dsonar.projectKey="my-project-key" `
            -Dsonar.organization="my-organization" `
            -Dsonar.host.url="${{ secrets.SONAR_HOST_URL }}" `
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"  # Ensure you use the correct GitHub secrets for your SonarQube instance
        shell: pwsh  # Use PowerShell Core shell in Windows
