name: Build and SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: self-hosted  # Windows self-hosted runner
    steps:

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.1
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}    # e.g., http://localhost:9000
          SONAR_TOKEN: ${{ secrets.SONAR_LOGIN }}          # Use a token instead of username/password
          SONAR_PROJECT_KEY: my_node_app                   # Replace with your project key
          SONAR_SOURCES: src                               # Adjust to your source folder
          SONAR_EXCLUSIONS: node_modules/**,dist/**,*.spec.js  # Exclude unnecessary files
          SONAR_SOURCE_ENCODING: UTF-8                     # Standard encoding
