name: SonarQube Integration for Node.js

on:
  push:
    branches:
      - main  # Adjust to your preferred branch
  pull_request:
    branches:
      - main  # Adjust to your preferred branch

jobs:
  sonarqube:
    name: SonarQube Scan with WSL
    runs-on: self-hosted  # Use the Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Disabling shallow clone to improve the relevancy of reporting

    - name: Install WSL (Ubuntu)
      run: |
        # Install WSL with Ubuntu if not already installed
        wsl --install -d Ubuntu

    - name: Install Node.js and Dependencies inside WSL
      run: |
        # Install Node.js and project dependencies inside WSL (Ubuntu)
        wsl bash -c "
          sudo apt update && sudo apt install -y curl unzip
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt install -y nodejs
          cd /mnt/c/$(System.DefaultWorkingDirectory)/ && npm install
        "

    - name: Run SonarQube Scan with prebuilt action inside WSL
      uses: sonarsource/sonarqube-scan-action@v1.2.0  # Use the prebuilt SonarQube scan action
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # SonarQube token stored in GitHub secrets
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # SonarQube URL stored in GitHub secrets
