name: Build
on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: self-hosted  # Self-hosted Windows runner
    
    steps:
      # Step 1: Checkout the source code
      - name: Checkout source code
        uses: actions/checkout@v3  # Latest stable version
        with:
          fetch-depth: 0  # Ensure full history for SonarQube analysis


      # Step 3: Run SonarQube Scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4  # Stable version of the SonarQube action
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
